name: CI

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "docs/**"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Run Tests
        run: pnpm test

  build_and_publish:
    needs: tests
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node-version: [24]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇️ Checkout
        id: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: 🥡 Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
        with:
          run_install: false

      - name: 🟢 Setup node
        id: setup-node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: 🧩 Install Dependencies
        id: install-dependencies
        run: pnpm install --frozen-lockfile

      - name: 🏗️ Build
        id: build-the-mono-repo
        run: |
          pnpm build

      - name: 📣 Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b # v1.8.0
        with:
          title: "chore(release): version packages 🦋"
          publish: pnpm publish:packages
          version: pnpm version:packages
          commit: "chore(release): version packages 🦋 [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
